trigger:
- master

resources:
  containers:          
    - container: sqltools
      image : mcr.microsoft.com/mssql-tools
    - container: testdb
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports: 
      - 1433:1433
      env:        
        SA_PASSWORD: "yourStrong(!)Password"
        ACCEPT_EULA: "Y"
      # command: "/bin/bash /opt/mssql/bin/sqlservr"
    # - container: flyway
    #   image: flyway/flyway:6.3.0
    #   env:
    #     FLYWAY_USER : 'SA'
    #     FLYWAY_PASSWORD : 'Test2019.!'
    #     FLYWAY_CONNECT_RETRIES : '30'
    #     FLYWAY_URL: 'jdbc:sqlserver://testdb:1433;databasename=master'
    #   command: "info"

pool:
  vmImage: 'ubuntu-18.04'

container: sqltools

services:
  testdb : testdb
  # flyway : flyway

steps:
 - script: |
    /opt/mssql-tools/bin/sqlcmd -S testdb -U SA -P yourStrong(!)Password

