FROM mcr.microsoft.com/mssql/server:2019-CTP3.0-ubuntu

RUN apt-get update \    
    # Verify git, process tools, lsb-release (common in install instructions for CLIs) installed
    && apt-get -y install git procps lsb-release 
